// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';
import {main} from '../models';

export function AddEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GetEntry(arg1:string):Promise<vault.PasswordEntry>;

export function GetVaultStats():Promise<main.VaultStats>;

export function HasStoredKeys():Promise<boolean>;

export function InitializeNewKeys(arg1:string,arg2:string):Promise<void>;

export function IsUnlocked():Promise<boolean>;

export function ListEntries():Promise<Array<vault.PasswordEntry>>;

export function Lock():Promise<void>;

export function ResetStoredKeys():Promise<void>;

export function Sync():Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateEntry(arg1:vault.PasswordEntry):Promise<void>;
