// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3, arg4);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetVaultStats() {
  return window['go']['main']['App']['GetVaultStats']();
}

export function HasStoredKeys() {
  return window['go']['main']['App']['HasStoredKeys']();
}

export function InitializeNewKeys(arg1, arg2) {
  return window['go']['main']['App']['InitializeNewKeys'](arg1, arg2);
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListEntries() {
  return window['go']['main']['App']['ListEntries']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
